env:
  browser: true
  es6: true
extends: "eslint:recommended"
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
  allowImportExportEverywhere: false
plugins:
  - babel
  - react
  - import
rules:
  strict: 0
#  require-await: 2
  no-var: 2
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - never
  react/jsx-uses-vars:
    - error
  react/jsx-uses-react:
    - error
  react/jsx-no-undef:
    - error
  no-console:
    - 0
  no-unused-vars:
    - 2
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  react/no-array-index-key: 2
#  react/jsx-no-bind: 2
  import/no-unresolved: 2
  import/prefer-default-export: 2
  import/named: 2
globals:
  process: true
  window: true
  document: true
  console: true
  __dirname: true
  require: true
  module: true
  FB: true
