version: "3.1"
services:
  app_aristotels:
    build: "./app_aristotels"
    ports:
      - "3000:3000"
    volumes:
      - ${BASE_DIR}/app_aristotels/:/usr/src/app/
    networks:
      - be
      - fe
  app_platon:
    build: "./app_platon"
    ports:
      - "5000:5000"
    volumes:
      - ${BASE_DIR}/app_platon/:/usr/src/app/
    networks:
      - be
      - fe
networks:
  fe:
    driver: "overlay"
  be:
    driver: "overlay"
