version: "3.1"
services:
  app_aristotels:
    build: "./app_aristotels"
    ports:
      - "8000:8000"
    volumes:
      - ${BASE_DIR}/app_aristotels/:/usr/src/app/
    networks:
      - be
      - fe
networks:
  fe:
    driver: "overlay"
  be:
    driver: "overlay"
